export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_INITIATE_SIGNUP = 'AUTH_INITIATE_SIGNUP';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_INITIATE_LOGIN = 'AUTH_INITIATE_LOGIN';
